version: '3'
services:
    gitlab:
      image: twang2218/gitlab-ce-zh:9.4
      restart: always
      hostname: 10.248.160.88
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://10.248.160.88:8080'
          gitlab_rails['gitlab_shell_ssh_port'] = 2222
          unicorn['port'] = 8888
          nginx['listen_port'] = 8080
      ports:
        - '8080:8080'
        - '8443:443'
        - '2222:22'
      volumes:
        - /data00/yizhou/git/gitlab/config:/etc/gitlab
        - /data00/yizhou/git/gitlab/repo:/var/opt/gitlab
        - /data00/yizhou/git/gitlab/logs:/var/log/gitlab

    jenkins:
      restart: always
      image: jenkins/jenkins
      container_name: docker_jenkins
      ports:
        - '8081:8080'
        - '50000:50000'
      volumes:
        - /data00/yizhou/git/jenkins/jenkins_home:/var/jenkins_home
      environment:
            JAVA_OPTS: '-Djava.util.logging.config.file=/var/jenkins_home/log.properties'